---
# handlers file for ansible-role-nagiosgraph

- name: nagios reload
  service: name="{{ nagiosgraph_nag_service }}" state=restarted
  
- name: apache reload
  service: name="{{ nagiosgraph_apache_service }}" state=restarted
